image: node:latest


pages:
  stage: deploy
  script:
    - npm install
    - ./node_modules/.bin/hexo g
  # This folder is cached between builds
  # http://docs.gitlab.com/ce/ci/yaml/README.html#cache
  cache:
    paths:
      - node_modules/

  artifacts:
    paths:
      - public
  only:
    - master
